"""
Hermes Content Pipeline - Stage 5: Human Review & Approval Queue
Stages AI-generated drafts into an actionable review queue with YAML frontmatter.
Allows operators to approve, reject, or edit drafts before publishing.
"""

import os
import json
import logging
import hashlib
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("HermesReviewQueue")


class ReviewQueue:
    def __init__(self, queue_dir: str = "queue/review", auto_approve: bool = False):
        self.queue_dir = queue_dir
        self.auto_approve = auto_approve
        os.makedirs(self.queue_dir, exist_ok=True)

    def _generate_id(self, url: str, title: str) -> str:
        """Create a compact unique identifier for the queue item."""
        digest = hashlib.md5(f"{url}{title}".encode("utf-8")).hexdigest()[:8]
        slug = "".join(c if c.isalnum() else "_" for c in title[:30].strip()).strip("_").lower()
        return f"{slug}_{digest}"

    def stage_item(self, item: Dict[str, Any]) -> str:
        """Save a drafted item to the review queue directory as a Markdown artifact."""
        draft = item.get("draft", {})
        title = draft.get("title", item.get("title", "Untitled Draft"))
        url = draft.get("source_url", item.get("url", ""))
        source = draft.get("source_name", item.get("source", "Unknown"))
        item_id = self._generate_id(url, title)

        initial_status = "approved" if self.auto_approve else "pending_review"
        filepath = os.path.join(self.queue_dir, f"{item_id}.md")

        # Format takeaways as markdown bullets
        takeaways_md = "\n".join(f"- {t}" for t in draft.get("takeaways", []))

        content = f"""---
id: "{item_id}"
title: "{title.replace('"', "'")}"
source: "{source}"
url: "{url}"
status: "{initial_status}"
created_at: "{datetime.now(timezone.utc).isoformat()}"
materiality_score: {item.get('evaluation', {}).get('materiality_score', 0)}
generated_by: "{draft.get('generated_by', 'Hermes')}"
---

# {title}

**Source**: [{source}]({url})  
**Status**: `{initial_status}`

---

## 📌 Executive Brief
{draft.get('executive_brief', '')}

---

## 💡 Key Takeaways
{takeaways_md}

---

## 📱 Social / Broadcast Draft
```text
{draft.get('social_draft', '')}
```

---
*Generated by Hermes Content Pipeline (Nous Research)*
"""
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

        logger.info(f"Staged draft [{initial_status}]: {filepath}")
        return filepath

    def list_queue(self) -> List[Dict[str, Any]]:
        """List all items currently in the review queue with status."""
        items = []
        for filename in os.listdir(self.queue_dir):
            if not filename.endswith(".md"):
                continue
            path = os.path.join(self.queue_dir, filename)
            try:
                with open(path, "r", encoding="utf-8") as f:
                    text = f.read()
                # Parse frontmatter
                if text.startswith("---"):
                    parts = text.split("---", 2)
                    if len(parts) >= 3:
                        meta = {}
                        for line in parts[1].strip().split("\n"):
                            if ":" in line:
                                k, v = line.split(":", 1)
                                meta[k.strip()] = v.strip().strip('"').strip("'")
                        meta["filepath"] = path
                        items.append(meta)
            except Exception as e:
                logger.error(f"Error reading {filename}: {e}")

        return sorted(items, key=lambda x: x.get("created_at", ""), reverse=True)

    def set_status(self, item_id: str, new_status: str) -> bool:
        """Update status of a queue item (approved, rejected, pending_review)."""
        for filename in os.listdir(self.queue_dir):
            if item_id in filename and filename.endswith(".md"):
                path = os.path.join(self.queue_dir, filename)
                with open(path, "r", encoding="utf-8") as f:
                    text = f.read()
                
                # Replace status in frontmatter
                updated = text.replace('status: "pending_review"', f'status: "{new_status}"')
                updated = updated.replace('status: "approved"', f'status: "{new_status}"')
                updated = updated.replace('status: "rejected"', f'status: "{new_status}"')
                updated = updated.replace(f"**Status**: `pending_review`", f"**Status**: `{new_status}`")
                updated = updated.replace(f"**Status**: `approved`", f"**Status**: `{new_status}`")
                
                with open(path, "w", encoding="utf-8") as f:
                    f.write(updated)
                logger.info(f"Updated {filename} -> {new_status}")
                return True
        return False

    def get_approved_items(self) -> List[Dict[str, Any]]:
        """Retrieve all items with approved status ready for publishing."""
        return [it for it in self.list_queue() if it.get("status") == "approved"]


if __name__ == "__main__":
    queue = ReviewQueue("queue/review", auto_approve=True)
    sample_item = {
        "title": "Hermes Agent Autonomous Pipeline Test",
        "url": "https://hermes-agent.nousresearch.com",
        "source": "Nous Research",
        "evaluation": {"materiality_score": 9},
        "draft": {
            "title": "Hermes Agent Autonomous Pipeline Test",
            "executive_brief": "Testing the automated staging queue.",
            "takeaways": ["Fast execution", "Safe approval workflow"],
            "social_draft": "Testing Hermes Agent queue."
        }
    }
    staged_path = queue.stage_item(sample_item)
    print("Staged to:", staged_path)
    print("Pending/Approved items in queue:", len(queue.list_queue()))
